### ISSUE TITLE
cannot use meta data item id

### ISSUE THREAD

**Issue by SayaAEP** [KingOfTurkey38/MineReset38#1]
`/mine addblock wood 162:1 50`

get `error invalid value '162:1 50' for argument #2`

**Comment by SayaAEP** [comment]
item id 162:1 is dark_oak_log

**Comment by KingOfTurkey38** [comment]
I see, I'll add block meta support soon

**Comment by KingOfTurkey38** [comment]
Added support for it in the latest version.

**Comment by SayaAEP** [comment]
> Added support for it in the latest version.

yey

**Comment by SayaAEP** [comment]
> Added support for it in the latest version.

cannot /mine addblock wood 17:1 50

**Comment by Endermanbugzjfc** [comment]
> > Added support for it in the latest version.
> 
> cannot /mine addblock wood 17:1 50

You can only add one block in each line of command.

**Comment by Endermanbugzjfc** [comment]
/mine addblock **wood** **17:1** 50

Bolded words are block IDs. Remove either one.

**Comment by KingOfTurkey38** [comment]
https://github.com/KingOfTurkey38/MineReset38/blob/b41fefe6150bc33b436784400971f0470faedf18/src/kingofturkey38/minereset38/commands/MineCommand.php#L23

Op za 5 nov. 2022 16:20 schreef TukangM ***@***.***>:
