### ISSUE TITLE
No safe data

### ISSUE THREAD

**Issue by usser1976** [KingOfTurkey38/MineReset38#3]
When you create a mine, the data is not written in the .json. At the restart, everything is gone.

**Comment by ghost** [comment]
> Quando você cria uma mina, os dados não são gravados no .json. Na reinicialização, tudo se foi.

for me it's fine, download the latest version of the plugin or make sure there aren't others getting in the way!

**Comment by usser1976** [comment]
Unfortunately, the problem remains with me to this day :(
