### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ghost** [KingOfTurkey38/MineReset38#7]
Can Remove messages in config.yml when mine reset

**Comment by Endermanbugzjfc** [comment]
> Can Remove messages in config.yml when mine reset

Do you mean hot-reload config.yml?

**Comment by ghost** [comment]
no, it would be the possibility to remove the warning message that the mine has reset, it's annoying

> > Can Remove messages in config.yml when mine reset
> 
> Do you mean hot-reload config.yml?

no, it would be the possibility to remove the warning message that the mine has reset, it's annoying

**Comment by Endermanbugzjfc** [comment]
> no, it would be the possibility to remove the warning message that the mine has reset, it's annoying
> 
> 
> 
> > > Can Remove messages in config.yml when mine reset
> 
> > 
> 
> > Do you mean hot-reload config.yml?
> 
> 
> 
> no, it would be the possibility to remove the warning message that the mine has reset, it's annoying

Try to set the message to an empty string.

**Comment by ghost** [comment]
> > no, it would be the possibility to remove the warning message that the mine has reset, it's annoying
> > > > Can Remove messages in config.yml when mine reset
> > 
> > 
> > > 
> > 
> > 
> > > Do you mean hot-reload config.yml?
> > 
> > 
> > no, it would be the possibility to remove the warning message that the mine has reset, it's annoying
> 
> Try to set the message to an empty string.

spam empty lines in chat lol
