### ISSUE TITLE
Another Problem :/

### ISSUE THREAD

**Issue by ghost** [KingOfTurkey38/MineReset38#9]
Console log on load plugin: 

NOTICE: `yield $generator` has been deprecated, please use `yield from $generator` instead.

**Comment by Endermanbugzjfc** [comment]
> Console log on load plugin:
> 
> NOTICE: `yield $generator` has been deprecated, please use `yield from $generator` instead.

It is just a warning that you can ignore. If  `yield` really crashes the server in the future, the author should realize when testing.

**Comment by Endermanbugzjfc** [comment]
# #10
